### ISSUE TITLE
temporary home for read.bam

### ISSUE THREAD

**Issue by mskilab** [mskilab/skitools#2]
read.bam has disappeared!! we need it to be somewhere for essential mskilab activities .. 

thanks

**Comment by walaj** [comment]
Can you make a new repos for all of these? We just need a name. Seems like they all have a unified purpose (bam access) and keeping separate from the skitools catch-all would be easier to manage

**Comment by mskilab** [comment]
ok sounds good - though i thought you were in process of making that ie a package that holds all the Rsamtools utility functions

let's call it bamUtils - I'll initialize, can you add to it all the stuff u took out of gUtils?

**Comment by walaj** [comment]
Yeah sounds good. I was just waiting for the new repos

**Comment by KhagayN** [comment]
I've been moving the functions that have been removed from gUtils into skitools. All the non-rmstall utils functions have been moved and a few of the rmstall utils have been moved as well. Should I continue adding the rmstall utils functions in skitools or move them into bamUtils.

**Comment by imielinski** [comment]
Hi Khagay -

By rmstall do you mean rsamtools?

Maybe check with Jeremiah, since he’s hooking bamUtils.  Once he’s made that, then we can do a diff of the old gUtils minus the new gUtils + bamutils, and whatever remains we put into skitools

Marcin

On March 30, 2016 at 3:24:36 PM, Khagay Nagdimov (notifications@github.commailto:notifications@github.com) wrote:

I've been moving the functions that have been removed from gUtils into skitools. All the non-rmstall utils functions have been moved and a few of the rmstall utils have been moved as well. Should I continue adding the rmstall utils functions in skitools or move them into bamUtils

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHubhttps://github.com/mskilab/skitools/issues/2#issuecomment-203594549

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by KhagayN** [comment]
Sorry, typo. When you made a decision Jeremiah, can you let me know what I should do?

**Comment by imielinski** [comment]
Jeremiah - if you’re not working on this right now, then maybe Khagay can take the first step

For example, Khagay you can send the functions that you think might be bamUtils and we can ok / neg them, and then you can put everything else into skitools

These are easy to spot actually - they are the functions with bam in the prefix or suffix ..

On March 30, 2016 at 3:34:42 PM, Khagay Nagdimov (notifications@github.commailto:notifications@github.com) wrote:

Sorry, typo. When you can, let me know what you think Jeremiah.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHubhttps://github.com/mskilab/skitools/issues/2#issuecomment-203599244

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by KhagayN** [comment]
Definitely.

**Comment by imielinski** [comment]
Khagay - when you do the setdiff can you use this gUtils.R version as the superset (from Feb 20)

https://github.com/mskilab/gUtils/blob/c9659fbb30f6b33a41535e87d945083ed97c8cb3/R/gUtils.R

On March 30, 2016 at 3:34:42 PM, Khagay Nagdimov (notifications@github.commailto:notifications@github.com) wrote:

Sorry, typo. When you can, let me know what you think Jeremiah.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHubhttps://github.com/mskilab/skitools/issues/2#issuecomment-203599244

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by KhagayN** [comment]
Okay. I was using the Dec. version before but, I'll double check the differences.

**Comment by imielinski** [comment]
Nice - thanks

Marcin

On March 30, 2016 at 3:58:58 PM, Khagay Nagdimov (notifications@github.commailto:notifications@github.com) wrote:

Okay. I was using the Dec. version before but, I'll double check the differences.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHubhttps://github.com/mskilab/skitools/issues/2#issuecomment-203608288

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by imielinski** [comment]
Khagay - also make sure to take into account gTrack in setdiff —> jeremiah moved some functions to there

so do

(February gUtils) - (current gTrack + current gUtils + current skitools)

and put this into skitools

I just removed a few things you had added because they were either in current gUtils or in gTrack

On March 30, 2016 at 3:58:58 PM, Khagay Nagdimov (notifications@github.commailto:notifications@github.com) wrote:

Okay. I was using the Dec. version before but, I'll double check the differences.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHubhttps://github.com/mskilab/skitools/issues/2#issuecomment-203608288

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by walaj** [comment]
Sorry out of the loop on this. Yeah, it would be great Khagay if you could set up the BamUtils repos to be an R package + TravisCI + Coveralls and testthat. Look at gUtils for examples, and RStudio helps a lot too. 

Right any function with bam prefix or which is relied on only by bam functions should go to bamUtils

**Comment by mskilab** [comment]
Great, Khagay - can u put into bamUtils any function from the Feb 20 gUtils
with
- bam in name
- cigar in name or description
- get_seq

**Comment by KhagayN** [comment]
Yup, will do.

**Comment by KhagayN** [comment]
skitools and bamUtils has been updated! working now on making bamUtils an R package + TravisCI + Coveralls and testthat.
